FROM debian:latest

# Set the working directory
WORKDIR /root

# Copy your setup script into the container
COPY pown.sh /root/pown.sh

# Make the script executable
RUN chmod +x /root/pown.sh

# Default to a shell for debugging
CMD ["/bin/bash"]
